version: '3.7'
services:
  task-api:
    stdin_open: true
    tty: true
    build:
      context: .
    ports:
      - '3000:3000'
    depends_on:
      - postgres
      # dockerfile: ./Dockerfile
  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASS}
      - POSTGRES_DB=${POSTGRES_DB}
      - PGDATA=/postgres-data
    ports:
      - ${POSTGRES_PORTS}
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./database/database.sql:/docker-entrypoint-initdb.d/database.sql
volumes:
  postgres-data:
